# Generated by Django 3.2.3 on 2021-05-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=400)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('SITE_URL', models.URLField()),
            ],
        ),
    ]
