# Generated by Django 3.2.3 on 2021-05-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0002_auto_20210524_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdata',
            old_name='created',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='sdata',
            old_name='modified',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='sdata',
            old_name='SITE_URL',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='sdata',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sdata',
            name='title',
        ),
        migrations.AddField(
            model_name='sdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdata',
            name='eventAttendanceMode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sdata',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sdata',
            name='performer_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
