# Generated by Django 3.2.3 on 2021-05-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0003_auto_20210525_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
