# Generated by Django 3.2.3 on 2021-05-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0004_alter_sdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
