# Generated by Django 3.2.3 on 2021-05-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0005_alter_sdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdata',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
