# Generated by Django 3.2.3 on 2021-05-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0006_sdata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='category',
            field=models.CharField(blank=True, default='Noting', max_length=256, null=True),
        ),
    ]
