# Generated by Django 3.2.3 on 2021-05-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0007_alter_sdata_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdata',
            old_name='url',
            new_name='Interesting_url',
        ),
        migrations.AddField(
            model_name='sdata',
            name='Non_interesting_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
