# Generated by Django 3.2.3 on 2021-05-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0009_auto_20210525_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestingurl',
            old_name='Interesting_url',
            new_name='Interesting_url1',
        ),
        migrations.RenameField(
            model_name='non_interesting_url',
            old_name='Non_interesting_url',
            new_name='Non_interesting_url1',
        ),
    ]
