# Generated by Django 3.2.3 on 2021-05-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0012_auto_20210525_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='category',
            field=models.TextField(blank=True, default='Noting', max_length=256, null=True),
        ),
    ]
