# Generated by Django 3.2.3 on 2021-05-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0014_alter_sdata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='category',
            field=models.CharField(blank=True, default='Noting', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='udata',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
