# Generated by Django 3.2.3 on 2021-05-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0015_auto_20210526_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='eventAttendanceMode',
            field=models.CharField(blank=True, default='Online', max_length=256, null=True),
        ),
    ]
