# Generated by Django 3.2.3 on 2021-05-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0016_alter_sdata_eventattendancemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udata',
            name='category',
            field=models.TextField(blank=True, default='Online Events', null=True),
        ),
    ]
