# Generated by Django 3.2.3 on 2021-05-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0017_alter_udata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udata',
            name='eventAttendanceMode',
            field=models.CharField(blank=True, default='Online', max_length=256, null=True),
        ),
    ]
