# Generated by Django 3.2.3 on 2021-05-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0018_alter_udata_eventattendancemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='eventAttendanceMode',
            field=models.CharField(blank=True, default='OnlineEventAttendanceMode', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='udata',
            name='eventAttendanceMode',
            field=models.CharField(blank=True, default='OnlineEventAttendanceMode', max_length=256, null=True),
        ),
    ]
