# Generated by Django 3.2.3 on 2021-05-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sApp', '0019_auto_20210525_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='performer_name',
            field=models.CharField(blank=True, default='None', max_length=256, null=True),
        ),
    ]
